# coding: utf-8

# flake8: noqa
"""
    IONOS CLOUD DBaaS MariaDB

    IONOS CLOUD Database as a Service (DBaaS) MariaDB v2 lets you provision and manage MariaDB clusters through a REST API. For product information, see [IONOS CLOUD MariaDB Guide](https://docs.ionos.com/cloud/databases/mariadb). 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from ionoscloud_dbaas_mariadb.models.backup import Backup
from ionoscloud_dbaas_mariadb.models.backup_create import BackupCreate
from ionoscloud_dbaas_mariadb.models.backup_ensure import BackupEnsure
from ionoscloud_dbaas_mariadb.models.backup_location import BackupLocation
from ionoscloud_dbaas_mariadb.models.backup_location_read import BackupLocationRead
from ionoscloud_dbaas_mariadb.models.backup_location_read_list import BackupLocationReadList
from ionoscloud_dbaas_mariadb.models.backup_read import BackupRead
from ionoscloud_dbaas_mariadb.models.backup_read_list import BackupReadList
from ionoscloud_dbaas_mariadb.models.cluster import Cluster
from ionoscloud_dbaas_mariadb.models.cluster_backup import ClusterBackup
from ionoscloud_dbaas_mariadb.models.cluster_create import ClusterCreate
from ionoscloud_dbaas_mariadb.models.cluster_create_properties import ClusterCreateProperties
from ionoscloud_dbaas_mariadb.models.cluster_ensure import ClusterEnsure
from ionoscloud_dbaas_mariadb.models.cluster_metadata import ClusterMetadata
from ionoscloud_dbaas_mariadb.models.cluster_read import ClusterRead
from ionoscloud_dbaas_mariadb.models.cluster_read_list import ClusterReadList
from ionoscloud_dbaas_mariadb.models.day_of_the_week import DayOfTheWeek
from ionoscloud_dbaas_mariadb.models.error import Error
from ionoscloud_dbaas_mariadb.models.error_messages_inner import ErrorMessagesInner
from ionoscloud_dbaas_mariadb.models.instance_configuration import InstanceConfiguration
from ionoscloud_dbaas_mariadb.models.links import Links
from ionoscloud_dbaas_mariadb.models.maintenance_window import MaintenanceWindow
from ionoscloud_dbaas_mariadb.models.mariadb_cluster_connection import MariadbClusterConnection
from ionoscloud_dbaas_mariadb.models.mariadb_cluster_states import MariadbClusterStates
from ionoscloud_dbaas_mariadb.models.mariadb_restore_cluster_from_backup import MariadbRestoreClusterFromBackup
from ionoscloud_dbaas_mariadb.models.mariadb_user import MariadbUser
from ionoscloud_dbaas_mariadb.models.mariadb_version import MariadbVersion
from ionoscloud_dbaas_mariadb.models.mariadb_version_read import MariadbVersionRead
from ionoscloud_dbaas_mariadb.models.mariadb_version_read_list import MariadbVersionReadList
from ionoscloud_dbaas_mariadb.models.metadata import Metadata
from ionoscloud_dbaas_mariadb.models.pagination import Pagination
