# coding: utf-8

"""
    IONOS CLOUD DBaaS MariaDB

    IONOS CLOUD Database as a Service (DBaaS) MariaDB v2 lets you provision and manage MariaDB clusters through a REST API. For product information, see [IONOS CLOUD MariaDB Guide](https://docs.ionos.com/cloud/databases/mariadb). 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from ionoscloud_dbaas_mariadb.models.cluster_read import ClusterRead
from ionoscloud_dbaas_mariadb.models.links import Links
from typing import Optional, Set
from typing_extensions import Self

class ClusterReadList(BaseModel):
    """
    ClusterReadList
    """ # noqa: E501
    offset: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="The offset specified in the request (if none was specified, the default offset is 0). ")
    limit: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="The limit specified in the request (if none was specified, use the endpoint's default pagination limit). ")
    links: Optional[Links] = Field(default=None, alias="_links")
    id: Optional[StrictStr] = Field(default=None, description="ID of the list of Cluster resources.")
    type: Optional[StrictStr] = Field(default=None, description="The type of the resource.")
    href: Optional[StrictStr] = Field(default=None, description="The URL of the list of Cluster resources.")
    items: Optional[List[ClusterRead]] = Field(default=None, description="The list of Cluster resources.")
    __properties: ClassVar[List[str]] = ["offset", "limit", "_links", "id", "type", "href", "items"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClusterReadList from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict['_links'] = self.links.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in items (list)
        _items = []
        if self.items:
            for _item_items in self.items:
                if _item_items:
                    _items.append(_item_items.to_dict())
            _dict['items'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClusterReadList from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "offset": obj.get("offset"),
            "limit": obj.get("limit"),
            "_links": Links.from_dict(obj["_links"]) if obj.get("_links") is not None else None,
            "id": obj.get("id"),
            "type": obj.get("type"),
            "href": obj.get("href"),
            "items": [ClusterRead.from_dict(_item) for _item in obj["items"]] if obj.get("items") is not None else None
        })
        return _obj


