# coding: utf-8

"""
    IONOS CLOUD DBaaS MariaDB

    IONOS CLOUD Database as a Service (DBaaS) MariaDB v2 lets you provision and manage MariaDB clusters through a REST API. For product information, see [IONOS CLOUD MariaDB Guide](https://docs.ionos.com/cloud/databases/mariadb). 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from ionoscloud_dbaas_mariadb.models.cluster_backup import ClusterBackup
from ionoscloud_dbaas_mariadb.models.instance_configuration import InstanceConfiguration
from ionoscloud_dbaas_mariadb.models.maintenance_window import MaintenanceWindow
from ionoscloud_dbaas_mariadb.models.mariadb_cluster_connection import MariadbClusterConnection
from ionoscloud_dbaas_mariadb.models.mariadb_restore_cluster_from_backup import MariadbRestoreClusterFromBackup
from ionoscloud_dbaas_mariadb.models.mariadb_user import MariadbUser
from typing import Optional, Set
from typing_extensions import Self

class ClusterCreateProperties(BaseModel):
    """
    ClusterCreateProperties
    """ # noqa: E501
    name: Optional[Annotated[str, Field(min_length=2, strict=True, max_length=63)]] = Field(default=None, description="The name of your MariaDB cluster. Must be 63 characters or less and must begin and end with an alphanumeric character (`[a-z0-9A-Z]`) with dashes (`-`), underscores (`_`), dots (`.`), and alphanumerics between. ")
    description: Optional[StrictStr] = Field(default=None, description="Human-readable description for the cluster.")
    version: Optional[StrictStr] = Field(default=None, description="The MariaDB version for the cluster. Use GET /versions to retrieve the list of supported versions. To upgrade, provide a version listed in canUpgradeTo for the current version. Downgrades are not supported. ")
    instances: Optional[InstanceConfiguration] = None
    connection: Optional[MariadbClusterConnection] = None
    maintenance_window: Optional[MaintenanceWindow] = Field(default=None, alias="maintenanceWindow")
    credentials: Optional[MariadbUser] = None
    restore_from_backup: Optional[MariadbRestoreClusterFromBackup] = Field(default=None, alias="restoreFromBackup")
    logs_enabled: Optional[StrictBool] = Field(default=None, description="Allows or disallows the collection and reporting of logs for this cluster's observability. If the observability service is not activated on the contract, this setting is accepted but has no effect; log collection will not be enabled until the observability service is activated. ", alias="logsEnabled")
    metrics_enabled: Optional[StrictBool] = Field(default=None, description="Allows or disallows the collection and reporting of metrics for this cluster's observability. If the observability service is not activated on the contract, this setting is accepted but has no effect; metric collection will not be enabled until the observability service is activated. ", alias="metricsEnabled")
    backup: Optional[ClusterBackup] = None
    __properties: ClassVar[List[str]] = ["name", "description", "version", "instances", "connection", "maintenanceWindow", "credentials", "restoreFromBackup", "logsEnabled", "metricsEnabled", "backup"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ClusterCreateProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of instances
        if self.instances:
            _dict['instances'] = self.instances.to_dict()
        # override the default output from pydantic by calling `to_dict()` of connection
        if self.connection:
            _dict['connection'] = self.connection.to_dict()
        # override the default output from pydantic by calling `to_dict()` of maintenance_window
        if self.maintenance_window:
            _dict['maintenanceWindow'] = self.maintenance_window.to_dict()
        # override the default output from pydantic by calling `to_dict()` of credentials
        if self.credentials:
            _dict['credentials'] = self.credentials.to_dict()
        # override the default output from pydantic by calling `to_dict()` of restore_from_backup
        if self.restore_from_backup:
            _dict['restoreFromBackup'] = self.restore_from_backup.to_dict()
        # override the default output from pydantic by calling `to_dict()` of backup
        if self.backup:
            _dict['backup'] = self.backup.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ClusterCreateProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "version": obj.get("version"),
            "instances": InstanceConfiguration.from_dict(obj["instances"]) if obj.get("instances") is not None else None,
            "connection": MariadbClusterConnection.from_dict(obj["connection"]) if obj.get("connection") is not None else None,
            "maintenanceWindow": MaintenanceWindow.from_dict(obj["maintenanceWindow"]) if obj.get("maintenanceWindow") is not None else None,
            "credentials": MariadbUser.from_dict(obj["credentials"]) if obj.get("credentials") is not None else None,
            "restoreFromBackup": MariadbRestoreClusterFromBackup.from_dict(obj["restoreFromBackup"]) if obj.get("restoreFromBackup") is not None else None,
            "logsEnabled": obj.get("logsEnabled"),
            "metricsEnabled": obj.get("metricsEnabled"),
            "backup": ClusterBackup.from_dict(obj["backup"]) if obj.get("backup") is not None else None
        })
        return _obj


