# coding: utf-8

"""
    IONOS CLOUD DBaaS MariaDB

    IONOS CLOUD Database as a Service (DBaaS) MariaDB v2 lets you provision and manage MariaDB clusters through a REST API. For product information, see [IONOS CLOUD MariaDB Guide](https://docs.ionos.com/cloud/databases/mariadb). 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class InstanceConfiguration(BaseModel):
    """
    InstanceConfiguration
    """ # noqa: E501
    count: Optional[Annotated[int, Field(le=5, strict=True, ge=1)]] = Field(default=None, description="The total number of instances in the cluster. A value of 1 creates a single-instance cluster. Values from 2 to 5 create a replicated cluster with one primary and n-1 secondary instances. ")
    ram: Optional[Annotated[int, Field(le=240, strict=True, ge=4)]] = Field(default=None, description="The amount of memory (RAM) per instance in gigabytes (GB). On update, RAM can be increased or decreased.")
    cores: Optional[Annotated[int, Field(le=62, strict=True, ge=1)]] = Field(default=None, description="The number of CPU cores per instance. On update, cores can be increased or decreased.")
    storage_size: Optional[Annotated[int, Field(le=4096, strict=True, ge=10)]] = Field(default=None, description="The amount of storage per instance in gigabytes (GB). On update, storage size can only be increased; it cannot be reduced. ", alias="storageSize")
    __properties: ClassVar[List[str]] = ["count", "ram", "cores", "storageSize"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of InstanceConfiguration from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of InstanceConfiguration from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "count": obj.get("count"),
            "ram": obj.get("ram"),
            "cores": obj.get("cores"),
            "storageSize": obj.get("storageSize")
        })
        return _obj


