# coding: utf-8

"""
    IONOS CLOUD DBaaS MariaDB

    IONOS CLOUD Database as a Service (DBaaS) MariaDB v2 lets you provision and manage MariaDB clusters through a REST API. For product information, see [IONOS CLOUD MariaDB Guide](https://docs.ionos.com/cloud/databases/mariadb). 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MariadbClusterStates(str, Enum):
    """
    The current lifecycle state of the cluster. - `PROVISIONING`: The system is actively applying the changes. - `AVAILABLE`: The resource is fully operational with no pending changes. - `UPDATING`: A modification is in progress. - `DESTROYING`: The resource is being deleted. - `FAILED`: The provisioning failed due to an internal error. 
    """

    """
    allowed enum values
    """
    PROVISIONING = 'PROVISIONING'
    AVAILABLE = 'AVAILABLE'
    UPDATING = 'UPDATING'
    DESTROYING = 'DESTROYING'
    FAILED = 'FAILED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MariadbClusterStates from a JSON string"""
        return cls(json.loads(json_str))


