# coding: utf-8

"""
    IONOS CLOUD DBaaS MariaDB

    IONOS CLOUD Database as a Service (DBaaS) MariaDB v2 lets you provision and manage MariaDB clusters through a REST API. For product information, see [IONOS CLOUD MariaDB Guide](https://docs.ionos.com/cloud/databases/mariadb). 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MariadbClusterConnection(BaseModel):
    """
    Connection information of the MariaDB cluster. 
    """ # noqa: E501
    datacenter_id: Optional[StrictStr] = Field(default=None, description="The data center to connect your instance to.", alias="datacenterId")
    lan_id: Optional[StrictStr] = Field(default=None, description="The numeric LAN ID to connect your instance to.", alias="lanId")
    primary_instance_address: Optional[StrictStr] = Field(default=None, description="Assigns the IP address and netmask to the cluster's primary instance, in CIDR notation. Note the following unavailable IP ranges: 10.208.0.0/12 10.233.0.0/18 10.233.64.0/18 192.168.230.0/24 ", alias="primaryInstanceAddress")
    __properties: ClassVar[List[str]] = ["datacenterId", "lanId", "primaryInstanceAddress"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MariadbClusterConnection from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MariadbClusterConnection from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "datacenterId": obj.get("datacenterId"),
            "lanId": obj.get("lanId"),
            "primaryInstanceAddress": obj.get("primaryInstanceAddress")
        })
        return _obj


