# coding: utf-8

"""
    IONOS CLOUD DBaaS MariaDB

    IONOS CLOUD Database as a Service (DBaaS) MariaDB v2 lets you provision and manage MariaDB clusters through a REST API. For product information, see [IONOS CLOUD MariaDB Guide](https://docs.ionos.com/cloud/databases/mariadb). 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MariadbRestoreClusterFromBackup(BaseModel):
    """
    Restores the cluster from a backup. On cluster creation, set `sourceBackupId` (optionally `recoveryTargetDatetime`) to initialize the new cluster from an existing backup. On in-place modification, set `recoveryTargetDatetime` only; the restore source is inferred from the cluster's own backups. The current data is overwritten with the restored data, and the cluster may experience a brief period of downtime during this process. 
    """ # noqa: E501
    source_backup_id: Optional[StrictStr] = Field(default=None, description="UUID of the backup to restore from. Required for restore on cluster creation; not valid for in-place restore, where the source is inferred from the cluster's own backups. ", alias="sourceBackupId")
    recovery_target_datetime: Optional[datetime] = Field(default=None, description="Providing this value as an ISO 8601 timestamp causes the system to replay the backups up to the specified time. Optional on cluster creation (the backup is applied in its entirety if omitted); required for in-place restore. ", alias="recoveryTargetDatetime")
    __properties: ClassVar[List[str]] = ["sourceBackupId", "recoveryTargetDatetime"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MariadbRestoreClusterFromBackup from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MariadbRestoreClusterFromBackup from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sourceBackupId": obj.get("sourceBackupId"),
            "recoveryTargetDatetime": obj.get("recoveryTargetDatetime")
        })
        return _obj


