# coding: utf-8

"""
    IONOS CLOUD DBaaS MariaDB

    IONOS CLOUD Database as a Service (DBaaS) MariaDB v2 lets you provision and manage MariaDB clusters through a REST API. For product information, see [IONOS CLOUD MariaDB Guide](https://docs.ionos.com/cloud/databases/mariadb). 

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class MariadbVersion(BaseModel):
    """
    MariaDB version.
    """ # noqa: E501
    version: Optional[StrictStr] = Field(default=None, description="The MariaDB version for the cluster. Use GET /versions to retrieve the list of supported versions. To upgrade, provide a version listed in canUpgradeTo for the current version. Downgrades are not supported. ")
    status: Optional[StrictStr] = Field(default=None, description="The support status of the version.")
    comment: Optional[StrictStr] = Field(default=None, description="Additional information about the version status.")
    can_upgrade_to: Optional[List[StrictStr]] = Field(default=None, description="List of versions that a cluster running this version can be upgraded to. Only versions in this list are accepted when updating the version field via PUT. ", alias="canUpgradeTo")
    __properties: ClassVar[List[str]] = ["version", "status", "comment", "canUpgradeTo"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MariadbVersion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MariadbVersion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "version": obj.get("version"),
            "status": obj.get("status"),
            "comment": obj.get("comment"),
            "canUpgradeTo": obj.get("canUpgradeTo")
        })
        return _obj


